

model: 
  name: "IA_voellmy"
  file: "surrogate_voellmy.pkl"
  input_dim: [2]
  output_dim: [1]
  debug: false
  max_workers: 1 # We need it to be 1 because rpy2 is not thread safe


calibration:
  sampler: dynesty # emcee or rwmcmc or dynesty
  sampler_params:
    rwmcmc:
        step_size: [0.05, 400] # step size for each parameter, mu and xi, respectively. I took 10% of the range. This should be modified/tuned according to the acceptance ratio from the real test.
        nwalkers:     1

    emcee:
      nwalkers:     100
      pool_type:    process   # serial | thread | process
      n_workers:    4

    dynesty:
      nlive:        500     # number of live points; more = more accurate evidence, slower
      dlogz:        0.01    # stopping criterion: stop when remaining ln(Z) contribution < this

  nburn:        1000
  nsteps:       2000
  parameters: ["mu", "xi"] 
  noise_parameters: ["sigma"]
  calibrate_noise: false
  noise_sigma: 0.05
  data: ["ImpactArea"]
  likelihood: normal
  priors:
    - name: mu
      distribution:
        type: uniform     
        attribute:
          lower_bound: 2.e-02
          upper_bound: 5.e-01
    - name: xi
      distribution:
        type: uniform     
        attribute:
          lower_bound: 4.e+02 
          upper_bound: 4.e+03
    - name: sigma
      distribution:
        type: uniform     
        attribute:
          lower_bound: 1.0e-9
          upper_bound: 0.5
